# Generated by Django 6.0.1 on 2026-02-06 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=200, verbose_name='Category Name')),
                ('url_title', models.CharField(max_length=200, verbose_name='Category URL Title')),
                ('is_active', models.BooleanField(verbose_name='Category Status')),
                ('is_delete', models.BooleanField(verbose_name='Product Delete Status')),
            ],
            options={
                'verbose_name': 'Product Category',
                'verbose_name_plural': 'Product Categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('price', models.IntegerField(verbose_name='Product Price')),
                ('shot_description', models.CharField(max_length=360, null=True, verbose_name='Product Short Description')),
                ('description', models.TextField(verbose_name='Product Description')),
                ('is_active', models.BooleanField(default=False, verbose_name='Product Status')),
                ('slug', models.SlugField(blank=True, default='', max_length=200, unique=True)),
                ('is_delete', models.BooleanField(verbose_name='Product Delete Status')),
                ('category', models.ManyToManyField(related_name='product_categories', to='product_module.productcategory', verbose_name='Categories')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.CreateModel(
            name='ProductTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(db_index=True, max_length=200, verbose_name='Tag Caption')),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_tags', to='product_module.product')),
            ],
            options={
                'verbose_name': 'Product Tag',
                'verbose_name_plural': 'Products Tags',
            },
        ),
    ]
