# Generated by Django 6.0.1 on 2026-02-06 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='shot_description',
            new_name='short_description',
        ),
    ]
