# Generated by Django 6.0.1 on 2026-03-29 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0004_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='productbrand',
            name='url_title',
            field=models.CharField(default='url_title', max_length=200, verbose_name='Brand URL Title'),
            preserve_default=False,
        ),
    ]
