# Generated by Django 6.0.1 on 2026-03-29 20:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0005_productbrand_url_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_categories', to='product_module.productcategory'),
        ),
        migrations.AlterField(
            model_name='productbrand',
            name='title',
            field=models.CharField(db_index=True, max_length=200, verbose_name='Brand Name'),
        ),
        migrations.AlterField(
            model_name='productbrand',
            name='url_title',
            field=models.CharField(db_index=True, max_length=200, verbose_name='Brand URL Title'),
        ),
    ]
