# Generated by Django 6.0.1 on 2026-04-05 07:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0008_productvisit'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/products/gallery', verbose_name='Gallery Image')),
                ('image_alt', models.CharField(blank=True, max_length=200, null=True, verbose_name='Image Alt Text')),
                ('is_main', models.BooleanField(default=False, verbose_name='Main Image')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Display Order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='product_module.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Product Gallery Image',
                'verbose_name_plural': 'Product Gallery Images',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
