# Generated by Django 6.0.4 on 2026-04-13 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0009_productgallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Product Description'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_fa',
            field=models.TextField(null=True, verbose_name='Product Description'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_it',
            field=models.TextField(null=True, verbose_name='Product Description'),
        ),
        migrations.AddField(
            model_name='product',
            name='short_description_en',
            field=models.CharField(max_length=360, null=True, verbose_name='Product Short Description'),
        ),
        migrations.AddField(
            model_name='product',
            name='short_description_fa',
            field=models.CharField(max_length=360, null=True, verbose_name='Product Short Description'),
        ),
        migrations.AddField(
            model_name='product',
            name='short_description_it',
            field=models.CharField(max_length=360, null=True, verbose_name='Product Short Description'),
        ),
        migrations.AddField(
            model_name='product',
            name='title_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='title_fa',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='title_it',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='productbrand',
            name='title_en',
            field=models.CharField(db_index=True, max_length=200, null=True, verbose_name='Brand Name'),
        ),
        migrations.AddField(
            model_name='productbrand',
            name='title_fa',
            field=models.CharField(db_index=True, max_length=200, null=True, verbose_name='Brand Name'),
        ),
        migrations.AddField(
            model_name='productbrand',
            name='title_it',
            field=models.CharField(db_index=True, max_length=200, null=True, verbose_name='Brand Name'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='title_en',
            field=models.CharField(db_index=True, max_length=200, null=True, verbose_name='Category Name'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='title_fa',
            field=models.CharField(db_index=True, max_length=200, null=True, verbose_name='Category Name'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='title_it',
            field=models.CharField(db_index=True, max_length=200, null=True, verbose_name='Category Name'),
        ),
        migrations.AddField(
            model_name='producttag',
            name='caption_en',
            field=models.CharField(db_index=True, max_length=200, null=True, verbose_name='Tag Caption'),
        ),
        migrations.AddField(
            model_name='producttag',
            name='caption_fa',
            field=models.CharField(db_index=True, max_length=200, null=True, verbose_name='Tag Caption'),
        ),
        migrations.AddField(
            model_name='producttag',
            name='caption_it',
            field=models.CharField(db_index=True, max_length=200, null=True, verbose_name='Tag Caption'),
        ),
    ]
