# Generated by Django 6.0.1 on 2026-02-18 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=200, verbose_name='Site Name')),
                ('site_url', models.CharField(max_length=200, verbose_name='Site URL')),
                ('email', models.CharField(verbose_name='Site Email')),
                ('phone', models.CharField(max_length=20, verbose_name='Site Phone Number')),
                ('address', models.TextField(verbose_name='Site Address')),
                ('fax', models.CharField(max_length=20, verbose_name='Site Fax')),
                ('logo', models.ImageField(upload_to='images/site_setting', verbose_name='Site Logo')),
                ('copy_right', models.TextField(verbose_name='Site Copy Right')),
                ('about_us_text', models.TextField(verbose_name='About Us')),
                ('is_main_setting', models.BooleanField(default=True, verbose_name='Main Site Setting')),
            ],
            options={
                'verbose_name': 'Site Setting',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
