# Generated by Django 6.0.1 on 2026-02-20 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0002_footerlinkbox_footerlink'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Slider Title')),
                ('sub_title', models.CharField(max_length=200, verbose_name='Slider Sub Title')),
                ('url', models.URLField(max_length=500, verbose_name='Slider URL')),
                ('url_title', models.CharField(max_length=200, verbose_name='Slider URL Title')),
                ('image', models.ImageField(upload_to='images/slider', verbose_name='Slider Image')),
                ('is_active', models.BooleanField(default=True, verbose_name='Slider Status')),
            ],
            options={
                'verbose_name': 'Slider',
                'verbose_name_plural': 'Sliders',
            },
        ),
    ]
