# Generated by Django 6.0.1 on 2026-04-03 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0003_slider'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Banner Title')),
                ('url', models.URLField(max_length=500, verbose_name='Banner URL')),
                ('image', models.ImageField(upload_to='images/banner', verbose_name='Banner Image')),
                ('is_active', models.BooleanField(default=True, verbose_name='Banner Status')),
            ],
            options={
                'verbose_name': 'Advertising Banner',
                'verbose_name_plural': 'Advertising Banners',
            },
        ),
    ]
