# Generated by Django 6.0.1 on 2026-04-03 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0004_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='position',
            field=models.CharField(choices=[('product_list', 'Product List'), ('product_detail', 'Product Detail')], default='product_list', max_length=20, verbose_name='Banner Position'),
            preserve_default=False,
        ),
    ]
