# Generated by Django 6.0.4 on 2026-04-13 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0005_banner_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='title_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Banner Title'),
        ),
        migrations.AddField(
            model_name='banner',
            name='title_fa',
            field=models.CharField(max_length=200, null=True, verbose_name='Banner Title'),
        ),
        migrations.AddField(
            model_name='banner',
            name='title_it',
            field=models.CharField(max_length=200, null=True, verbose_name='Banner Title'),
        ),
        migrations.AddField(
            model_name='footerlink',
            name='title_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='footerlink',
            name='title_fa',
            field=models.CharField(max_length=200, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='footerlink',
            name='title_it',
            field=models.CharField(max_length=200, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='footerlinkbox',
            name='title_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Footer Link Box Title'),
        ),
        migrations.AddField(
            model_name='footerlinkbox',
            name='title_fa',
            field=models.CharField(max_length=200, null=True, verbose_name='Footer Link Box Title'),
        ),
        migrations.AddField(
            model_name='footerlinkbox',
            name='title_it',
            field=models.CharField(max_length=200, null=True, verbose_name='Footer Link Box Title'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='about_us_text_en',
            field=models.TextField(null=True, verbose_name='About Us'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='about_us_text_fa',
            field=models.TextField(null=True, verbose_name='About Us'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='about_us_text_it',
            field=models.TextField(null=True, verbose_name='About Us'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='address_en',
            field=models.TextField(null=True, verbose_name='Site Address'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='address_fa',
            field=models.TextField(null=True, verbose_name='Site Address'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='address_it',
            field=models.TextField(null=True, verbose_name='Site Address'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='copy_right_en',
            field=models.TextField(null=True, verbose_name='Site Copy Right'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='copy_right_fa',
            field=models.TextField(null=True, verbose_name='Site Copy Right'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='copy_right_it',
            field=models.TextField(null=True, verbose_name='Site Copy Right'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='site_name_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Site Name'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='site_name_fa',
            field=models.CharField(max_length=200, null=True, verbose_name='Site Name'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='site_name_it',
            field=models.CharField(max_length=200, null=True, verbose_name='Site Name'),
        ),
        migrations.AddField(
            model_name='slider',
            name='sub_title_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Slider Sub Title'),
        ),
        migrations.AddField(
            model_name='slider',
            name='sub_title_fa',
            field=models.CharField(max_length=200, null=True, verbose_name='Slider Sub Title'),
        ),
        migrations.AddField(
            model_name='slider',
            name='sub_title_it',
            field=models.CharField(max_length=200, null=True, verbose_name='Slider Sub Title'),
        ),
        migrations.AddField(
            model_name='slider',
            name='title_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Slider Title'),
        ),
        migrations.AddField(
            model_name='slider',
            name='title_fa',
            field=models.CharField(max_length=200, null=True, verbose_name='Slider Title'),
        ),
        migrations.AddField(
            model_name='slider',
            name='title_it',
            field=models.CharField(max_length=200, null=True, verbose_name='Slider Title'),
        ),
        migrations.AddField(
            model_name='slider',
            name='url_title_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Slider URL Title'),
        ),
        migrations.AddField(
            model_name='slider',
            name='url_title_fa',
            field=models.CharField(max_length=200, null=True, verbose_name='Slider URL Title'),
        ),
        migrations.AddField(
            model_name='slider',
            name='url_title_it',
            field=models.CharField(max_length=200, null=True, verbose_name='Slider URL Title'),
        ),
    ]
