# Generated by Django 6.0.1 on 2026-02-21 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article_module', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='category',
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ManyToManyField(to='article_module.articlecategory', verbose_name='Category'),
        ),
    ]
