# Generated by Django 6.0.1 on 2026-02-21 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article_module', '0002_remove_article_category_article_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=400, null=True, unique=True, verbose_name='Article URL Title'),
        ),
        migrations.AlterField(
            model_name='articlecategory',
            name='url_title',
            field=models.CharField(max_length=300, unique=True, verbose_name='Category URL Title'),
        ),
    ]
