# Generated by Django 6.0.1 on 2026-02-26 16:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article_module', '0008_articlecomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlecomment',
            name='comment',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(1, message='نظر نمیتواند خالی باشد')], verbose_name='Comment'),
        ),
    ]
