# Generated by Django 6.0.4 on 2026-04-13 20:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article_module', '0009_alter_articlecomment_comment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='author_en',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='authored_articles', to=settings.AUTH_USER_MODEL, verbose_name='Author'),
        ),
        migrations.AddField(
            model_name='article',
            name='author_fa',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='authored_articles', to=settings.AUTH_USER_MODEL, verbose_name='Author'),
        ),
        migrations.AddField(
            model_name='article',
            name='author_it',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='authored_articles', to=settings.AUTH_USER_MODEL, verbose_name='Author'),
        ),
        migrations.AddField(
            model_name='article',
            name='content_en',
            field=models.TextField(null=True, verbose_name='Article Content'),
        ),
        migrations.AddField(
            model_name='article',
            name='content_fa',
            field=models.TextField(null=True, verbose_name='Article Content'),
        ),
        migrations.AddField(
            model_name='article',
            name='content_it',
            field=models.TextField(null=True, verbose_name='Article Content'),
        ),
        migrations.AddField(
            model_name='article',
            name='editor_en',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='edited_articles', to=settings.AUTH_USER_MODEL, verbose_name='Editor'),
        ),
        migrations.AddField(
            model_name='article',
            name='editor_fa',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='edited_articles', to=settings.AUTH_USER_MODEL, verbose_name='Editor'),
        ),
        migrations.AddField(
            model_name='article',
            name='editor_it',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='edited_articles', to=settings.AUTH_USER_MODEL, verbose_name='Editor'),
        ),
        migrations.AddField(
            model_name='article',
            name='short_description_en',
            field=models.CharField(max_length=360, null=True, verbose_name='Article Short Description'),
        ),
        migrations.AddField(
            model_name='article',
            name='short_description_fa',
            field=models.CharField(max_length=360, null=True, verbose_name='Article Short Description'),
        ),
        migrations.AddField(
            model_name='article',
            name='short_description_it',
            field=models.CharField(max_length=360, null=True, verbose_name='Article Short Description'),
        ),
        migrations.AddField(
            model_name='article',
            name='title_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='title_fa',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='title_it',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='articlecategory',
            name='title_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Category Name'),
        ),
        migrations.AddField(
            model_name='articlecategory',
            name='title_fa',
            field=models.CharField(max_length=200, null=True, verbose_name='Category Name'),
        ),
        migrations.AddField(
            model_name='articlecategory',
            name='title_it',
            field=models.CharField(max_length=200, null=True, verbose_name='Category Name'),
        ),
    ]
