# Generated by Django 6.0.1 on 2026-02-24 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0002_remove_user_phone_number_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='about_user',
            field=models.TextField(blank=True, null=True, verbose_name='About User'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='images/avatars', verbose_name='Avatar'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email_active_code',
            field=models.CharField(max_length=100, verbose_name='Email Active Code'),
        ),
    ]
